### PR TITLE
Make special http request for facebook oAuth.

### PR DESCRIPTION
**Pull request by lukert33**

### CODE REVIEW

**Comment by jorgerc85** [comment]
I added the new domain on the facebook settings page. Can you check to confirm it's working for you? We might not need to add this change if it works.

**Comment by lukert33** [comment]
It was already on there from my trying to make it work, yesterday, wasn't
it? The issue, I think, is that our domain interfaces with heroku as a
subdomain--which is why I have to prepend www. in the manifest file.
Facebook seems to only want to work with raw domains, but that won't route
us correctly through the api.

**Comment by jorgerc85** [comment]
It was there but the urls in the 'Valid OAuth redirect URIs' section in the advanced tab where wrong. One of them had a typo also. If you try going through the Oauth process now and you get to the instructions page on our server it should work fine.

**Comment by lukert33** [comment]
YES!! It does work. Thank you. Please do go ahead and close my PR then.

**Pull request closed without merging**
