### PR TITLE
Char encoding

### PR DESCRIPTION
**Pull request by jorgerc85**

### CODE REVIEW

**Comment by lukert33** [comment]
I think you're on to something, but this kind of encoding may need some better support on our back end. Twitter counts this encoding as a bunch of characters and rejected my 140 char (per echo that_ tweet).  As of now this is what posts on facebook: 

"To create the bridges, Wisteria vinesetcode4osqbr...etcode4csqbrgrown to extraordinary lengths from either side of the river." @mordicai https://echoko.herokuapp.com/o/ezxts26C

when I tried to post:

"To create the bridges, Wisteria vines[...] to extraordinary lengths from either side of the river." @mordicai https://echoko.herokuapp.com/o/ezxts26C

**Comment by jorgerc85** [comment]
I made a pull request for the decoding on the API repo.
https://github.com/echoThat/echo_that_api/pull/2

**Comment by lukert33** [comment]
Just saw that. Staging now to heroku to test.

**Comment by lukert33** [comment]
Success!

**Pull request merged**
